[project]
name = "ai-stock-screener-agno-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=2.3.24",
    "groq>=1.0.0",
    "openai>=2.14.0",
    "plotly>=6.5.1",
    "python-dotenv>=1.2.1",
    "streamlit>=1.52.2",
    "tavily-python>=0.7.17",
    "yfinance>=1.0",
]
