[theme]
base = "dark"

# General color setup
textColor = "#ffffff"
primaryColor = "#4f6cb7"
backgroundColor = "#4172f7"
secondaryBackgroundColor = "#03081a"

# Widgets


# Dataframes
dataframeHeaderBackgroundColor = "#1d293d"

# Base text
font = "'Nunito':https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&display=swap"
baseFontWeight = 300
baseFontSize = 14

# Heading text
headingFont = "Nunito"
headingFontWeights = [300, 400, 400, 300, 300, 300]
headingFontSizes = ["2.5rem", "1.5rem", "1rem"]