[theme]
base = "dark"

# General color setup
textColor = "#e2e8f0"
primaryColor = "#0F1D41"
backgroundColor = "#132452"
secondaryBackgroundColor = "#0f172b"

# Widgets
showWidgetBorder = true
borderColor = "#314158"

# Dataframes
dataframeHeaderBackgroundColor = "#1d293d"

# Base text
font = "'Nunito':https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&display=swap"
baseFontWeight = 300
baseFontSize = 14

# Heading text
headingFont = "Nunito"
headingFontWeights = [300, 400, 400, 300, 300, 300]
headingFontSizes = ["2.5rem", "1.5rem", "1rem"]